# REST API

### Get All Profiles
### curl http://localhost:3000/profile
GET http://localhost:3000/profile

### Create New Profile
### curl -X POST http://localhost:3000/profile
POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "woraphong",
    "password": "aaa",
    "mobile": "0925452552",
    "cardId": "3242511255258"
}

### Get some profile by id
GET http://localhost:3000/profile/7645b518-749d-4c18-a2e3-93eb3a8d3a49xyz

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "www",
    "password": "ppp"
}