OLD file For test


### Get All Profiles
GET http://localhost:3000/profile

### Get Profile by ID
GET http://localhost:3000/profile/6afb93c4-f429-47d8-a1d8-c887b69332b4

### Create New Profile
POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "demo7",
    "password": "demo7",
    "mobile": "0352145890",
    "cardId": "3220100858126"
}

### Update Profile
PUT http://localhost:3000/profile/6afb93c4-f429-47d8-a1d8-c887b69332b4
Content-Type: application/json

{
    "username": "demo_edit",
    "mobile": "0999999999"
}

### Delete Profile
DELETE http://localhost:3000/profile/6afb93c4-f429-47d8-a1d8-c887b69332b4

### Encode  Class Sun 14 Sep test ok
POST http://localhost:3000/encode

### Decode  Class Sun 14 Sep test ok
POST http://localhost:3000/decode
