### Get All Profiles
GET http://localhost:3000/profile

### Get Profile by ID
GET http://localhost:3000/profile/6afb93c4-f429-47d8-a1d8-c887b69332b4

### Create New Profile
POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "demo3",
    "password": "demo3",
    "mobile": "0912345678",
    "cardId": "1234567890123"
}

### Update Profile
PUT http://localhost:3000/profile/6afb93c4-f429-47d8-a1d8-c887b69332b4
Content-Type: application/json

{
    "username": "demo3_edit",
    "mobile": "0999999999"
}

### Delete Profile
DELETE http://localhost:3000/profile/6afb93c4-f429-47d8-a1d8-c887b69332b4
